### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by chybhao666** [jericks/ShapefileCpp#1]
Hi Jared, 

I appreciate your fantastic work to wrap shapelib C APIs using C++ classes! I am from NVIDIA, we are working on a project to convert some HDMap format to SHP format. I would like to leverage your ShapefileCpp as a 3rdparty dependency in our codebase. Could you tell me what types of open source license you intend to use? Thanks a lot and Best Regards!

**Comment by jericks** [comment]
Hi Alex,

I just added an MIT license file to the repo.  I hope you find this useful.  Contributions would be much appreciated!

Jared

**Comment by chybhao666** [comment]
Thanks a lot, Jared!
